<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <AssemblyName>WrestlingAdmin</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationIcon>Resources\scoreboard.ico</ApplicationIcon>
    <NoWin32Manifest>true</NoWin32Manifest>
    <StartupObject>Wrestling.UI.Material.App</StartupObject>
    <SupportedOSPlatforms>windows</SupportedOSPlatforms>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="FluentResults" Version="4.0.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.0" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="MvvmDialogs" Version="9.1.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="PdfSharp" Version="6.1.1" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="System.Windows.Extensions" Version="9.0.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Wrestling.DataAccess\Wrestling.DataAccess.csproj" />
    <ProjectReference Include="..\Wrestling.Entities\Wrestling.Entities.csproj" />
    <ProjectReference Include="..\Wrestling.Providers\Wrestling.Providers.csproj" />
    <ProjectReference Include="..\Wrestling.UI.Utils\Wrestling.UI.Utils.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\30sec.png" />
    <Resource Include="Resources\30sec_cancel.png" />
    <Resource Include="Resources\Confirm.png" />
    <Resource Include="Resources\logo_img.ico" />
    <Resource Include="Resources\MainLogo.png" />
    <Resource Include="Resources\scoreboard.ico" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Images\DefaultLogo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\RosbosLogo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\SliderLogo.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\SingleGong.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\SingleGongBeep.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\TripleGong.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Sounds\TripleGongBeep.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
